#!/usr/bin/env node
/**
 * Compile the knowledge subset an agent needs for one task.
 *
 *   node knowledge/compile.mjs --task build --trade hvac --out app/KNOWLEDGE.md
 *   node knowledge/compile.mjs --task seo --trade hvac          # prints to stdout
 *
 * Reads manifest.json, resolves the ordered card list (always + byTrade), strips each
 * card's frontmatter, and emits one document with a TOC and a content hash.
 * Missing cards are listed as TODO stubs, not errors — the KB is built incrementally.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const KROOT = dirname(fileURLToPath(import.meta.url));
const args = process.argv.slice(2);
const opt = (f, d) => { const i = args.indexOf(f); return i >= 0 ? args[i + 1] : d; };
const task = opt("--task");
const trade = opt("--trade", "");
const out = opt("--out");

if (!task) {
  console.error("usage: node knowledge/compile.mjs --task <build|seo|managed> [--trade hvac] [--out path]");
  process.exit(2);
}

const manifest = JSON.parse(readFileSync(join(KROOT, "manifest.json"), "utf8"));
const block = manifest[task];
if (!block) { console.error(`unknown task "${task}". known: ${Object.keys(manifest).filter(k => k[0] !== "_")}`); process.exit(2); }

const ids = [
  ...(block.always || []),
  ...((trade && block.byTrade && block.byTrade[trade]) || []),
];

function stripFrontmatter(md) {
  const m = md.match(/^---\n([\s\S]*?)\n---\n?/);
  return { fm: m ? m[1] : "", body: m ? md.slice(m[0].length).trim() : md.trim() };
}

const parts = [];
const missing = [];
const included = [];

for (const id of ids) {
  const file = join(KROOT, id + ".md");
  if (!existsSync(file)) {
    missing.push(id);
    parts.push(`## ${id}\n\n> TODO: card not written yet (\`knowledge/${id}.md\`).`);
    continue;
  }
  const { body } = stripFrontmatter(readFileSync(file, "utf8"));
  included.push(id);
  parts.push(`<!-- card: ${id} -->\n${body}`);
}

const compiled = parts.join("\n\n---\n\n");
const hash = createHash("sha256").update(compiled).digest("hex").slice(0, 12);

const today = new Date().toISOString().slice(0, 10);
const header =
`---
title: Knowledge
purpose: Generated compilation of the knowledge cards for one task and trade (do not edit; edit the cards)
status: active
owner: c.t.cohen
updated: '${today}'
tier_scope: all
phase: operational
---

<!-- GENERATED by knowledge/compile.mjs — do not edit. Edit the cards in knowledge/. -->
# Fornax knowledge — task: ${task}${trade ? ` · trade: ${trade}` : ""}

Version: ${hash} · generated ${new Date().toISOString()}
Cards included (${included.length}): ${included.join(", ") || "(none)"}
${missing.length ? `Cards still TODO (${missing.length}): ${missing.join(", ")}` : ""}

---

`;

const doc = header + compiled + "\n";

if (out) {
  writeFileSync(join(KROOT, "..", out), doc);
  console.error(`wrote ${out} · ${included.length} cards · ${missing.length} todo · v${hash}`);
} else {
  process.stdout.write(doc);
}
